### ISSUE TITLE
Fix Postgres cache lookup issue

### ISSUE THREAD

**Issue by Fgerthoffert** [overture-stack/SONG#125]
Refer to tag "POSTGRES_CACHE_LOOKUP_ISSUE" of commit "5d148ae16bb22703ab3714be191d90e7ef96b020"

 

Executing the statement manually in psql works fine, however doesnt work using jdbi
```
Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.014 sec <<< FAILURE! - in org.icgc.dcc.song.server.StudyServiceTest
testReadStudy(org.icgc.dcc.song.server.StudyServiceTest) Time elapsed: 0.008 sec <<< ERROR!
org.skife.jdbi.v2.exceptions.UnableToExecuteStatementException: org.postgresql.util.PSQLException: ERROR: cache lookup failed for type 155933 [statement:"SELECT info from Info where id_type=:type AND id=:id", located:"SELECT info from Info where id_type=:type AND id=:id", rewritten:"SELECT info from Info where id_type=? AND id=?", arguments:{ positional:{}, named:{id:ABC123,type:Study}, finder:[]}]
at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2284)
at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2003)
at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:200)
at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:424)
at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:161)
at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:155)
at org.skife.jdbi.v2.SQLStatement.internalExecute(SQLStatement.java:1300)
at org.skife.jdbi.v2.Query.fold(Query.java:172)
at org.skife.jdbi.v2.Query.first(Query.java:267)
at org.skife.jdbi.v2.Query.first(Query.java:259)
at org.skife.jdbi.v2.sqlobject.ResultReturnThing$SingleValueResultReturnThing.result(ResultReturnThing.java:91)
at org.skife.jdbi.v2.sqlobject.ResultReturnThing.map(ResultReturnThing.java:32)
at org.skife.jdbi.v2.sqlobject.QueryHandler.invoke(QueryHandler.java:45)
at org.skife.jdbi.v2.sqlobject.SqlObject.invoke(SqlObject.java:147)
at org.skife.jdbi.v2.sqlobject.SqlObject$2.intercept(SqlObject.java:74)
at org.skife.jdbi.v2.sqlobject.CloseInternalDoNotUseThisClass$$EnhancerByCGLIB$$5b55381b.read(<generated>)
at org.icgc.dcc.song.server.service.InfoService.read(InfoService.java:47)
at org.icgc.dcc.song.server.service.StudyService.read(StudyService.java:53)
at org.icgc.dcc.song.server.StudyServiceTest.testReadStudy(StudyServiceTest.java:47)
```

Imported from: https://jira.oicr.on.ca/browse/DCC-5739

**Comment by rtisma** [comment]
Fixed in Issue #231  via PR #233 and commit cb8d6fd578bd5fc44eae24ff02caa5001de133d7
