### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [overture-stack/SONG#631]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 1.4.1. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary overture-song -w /tmp/ext overture-song==1.4.1
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting overture-song==1.4.1
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/ed1/8fbd429fc4e8b/overture-song-1.4.1.tar.gz (17 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-xg9f9uri/overture-song/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-xg9f9uri/overture-song/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-xg9f9uri/overture-song/pip-egg-info
         cwd: /tmp/pip-wheel-xg9f9uri/overture-song/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-xg9f9uri/overture-song/setup.py", line 167, in <module>
        run()
      File "/tmp/pip-wheel-xg9f9uri/overture-song/setup.py", line 67, in run
        with open_(path.join(here, 'docs/index.rst'), encoding='utf-8') as file_:
      File "/usr/lib/python3.8/codecs.py", line 905, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-wheel-xg9f9uri/overture-song/docs/index.rst'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by rtisma** [comment]
@thatch Thank you for finding this. I have pushed a compatible version 1.5.0.2 to PyPi and tested and everything should be good now.
